MySportsClub/Controllers/MembersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MySportsClub.Models;

namespace MySportsClub.Controllers
{
    [Authorize(Roles = "Admin,Desk")]
    public class MembersController : Controller
    {
        private readonly IMemberRepository repository;

        public MembersController(IMemberRepository context)
        {
            repository = context;
        }

        // GET: Members
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await repository.FindAllAsync());
        }

        // GET: Members/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await repository.FindAsync(id.Value);

            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // GET: Members/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Email,StartMembership")] Member member)
        {
            if (member.StartMembership.Date < DateTime.Now.Date)
            {
                ModelState.AddModelError("", "Date cannot be in the past.");
            }

            if (ModelState.IsValid)
            {
                await repository.InsertAsync(member);
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }

        // GET: Members/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await repository.FindAsync(id.Value);
            if (member == null)
            {
                return NotFound();
            }
            return View(member);
        }

        // POST: Members/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Email,StartMembership")] Member member)
        {
            if (id != member.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await repository.UpdateAsync(member);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await MemberExists(member.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }

        // GET: Members/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await repository.FindAsync(id.Value);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var member = await repository.FindAsync(id);
            await repository.DeleteAsync(member);
            return RedirectToAction(nameof(Index));
        }

        // GET: Workouts/Delete/5
        public async Task<IActionResult> DeleteEnrollment(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workout = await repository.FindAsync(id.Value);
            if (workout == null)
            {
                return NotFound();
            }

            return View(workout);
        }


        private async Task<bool> MemberExists(int id)
        {
            Member member = await repository.FindAsync(id);
            return member != null;
        }
    }
}

MySportsClub/Controllers/WorkoutsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MySportsClub.Models;
using MySportsClub.Services;

namespace MySportsClub.Controllers
{
    [Authorize]

    public class WorkoutsController : Controller
    {
        private readonly IWorkoutRepository workoutRepository;
        private readonly IMemberRepository memberRepository;
        private readonly IMailService mailService;

        // todo lesson 6-08: use constructor dependency injection for IMailService
        public WorkoutsController(
            IWorkoutRepository workoutRepository,
            IMemberRepository memberRepository,
            IMailService mailService) {
            this.workoutRepository = workoutRepository;
            this.memberRepository = memberRepository;
            this.mailService = mailService;
        }

        // GET: Workouts
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await workoutRepository.FindAllAsync());
        }


        // GET: Workouts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workout = await workoutRepository.FindAsync(id.Value);
            if (workout == null)
            {
                return NotFound();
            }

            return View(workout);
        }

        // GET: Workouts/Create
        [Authorize(Roles ="Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Workouts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,Location,StartTime,EndTime")] Workout workout)
        {
            if (workout.StartTime > workout.EndTime)
            {
                ModelState.AddModelError("", "end time of workout should be after start time.");
            }

            if (ModelState.IsValid)
            {
                await workoutRepository.InsertAsync(workout);
                return RedirectToAction(nameof(Index));
            }
            return View(workout);
        }

        // GET: Workouts/Edit/5
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workout = await workoutRepository.FindAsync(id.Value);
            if (workout == null)
            {
                return NotFound();
            }
            return View(workout);
        }

        // POST: Workouts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Title,Location,StartTime,EndTime")] Workout workout)
        {
            if (id != workout.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await workoutRepository.UpdateAsync(workout);
                return RedirectToAction(nameof(Index));
            }
            return View(workout);
        }

        // GET: Workouts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Workout workout = await workoutRepository.FindAsync(id.Value);
            if (workout == null)
            {
                return NotFound();
            }

            return View(workout);
        }
        [HttpPost]
        // POST: Workouts/SendMail
        public async Task SendMail() {
            MailRequest mailRequest = new() {
                To = "pjfmast@gmail.com",
                Subject = $"Testing MailKit service",
                Body = $"Hi, this is a test for the MailService."
            };
            await mailService.SendMailAsync(mailRequest);
        }

        // POST: Workouts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Workout workout = await workoutRepository.FindAsync(id);
            await workoutRepository.DeleteAsync(workout);

            // todo lesson 6-09 notify members when a workout is cancelled (deleted)
            await NotifyMembersDeletedWorkout(workout);

            return RedirectToAction(nameof(Index));
        }

        // todo lesson 6-10 use the MailService to send a mail to all members that the workout is cancelled
        private async Task NotifyMembersDeletedWorkout(Workout workout) {

            //MailRequest mailRequest = new MailRequest() {
            //    ToEmail = "some_member@gmail.com",
            //    Subject = $"workout {workout.Title} cancelled",
            //    Body = $"Hi, the workout {workout.Title} at {workout.StartTime} has been cancelled."
            //};
            //await mailService.SendMailAsync(mailRequest);

            // notify al members of cancelled workout:
            var members = await memberRepository.FindAllAsync();

            foreach (var member in members) {
                MailRequest mailRequest = new() {
                    To = member.Email,
                    Subject = $"workout {workout.Title} cancelled",
                    Body = $"Hi {member.Name}, the workout {workout.Title} at {workout.StartTime} has been cancelled."
                };
                await mailService.SendMailAsync(mailRequest);

            }
        }

        private async Task<bool> WorkoutExists(int id)
        {
            Workout workout = await workoutRepository.FindAsync(id);
            return workout != null;
        }
    }
}

MySportsClub/Views/Shared/_Layout.cshtml
@using  Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> signInManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sports Club</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MySportsClub.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sports Club</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Members" asp-action="Index">Members</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Workouts" asp-action="Index">Workouts</a>
                        </li>
                    </ul>
                     <ul class="navbar-nav ml-auto">
                        @* IsSignedIn(User) - Returns true if the principal has an identity with the application cookie identity *@
                        @* User: is System.Security.ClaimsPrincipal of the current logged in user.*@
                        @*todo statements in razor pages werken niet met de Razor style comments
                            maar wel op de onderstaande manier*@

                        <!--todo lesson 4-11: Laat login / logout zien afhankelijk van inlogstatus: -->
                        <!--Twee mogelijkheden: m.b.v. SignInMangager: -->
                        <!-- if (signInManager.IsSignedIn(User)) -->
                        <!-- of zoals hieronder algemener (niet alleen voor ASP.NET Identity)
                                zie ook: https://stackoverflow.com/questions/48307099/signinmanager-issignedinuser-versus-user-identity-isauthenticated
                        -->
                        @if (User?.Identity?.IsAuthenticated ?? false) {
                            <li class="nav-item">
                                <form method="post" asp-action="logout" asp-controller="users">
                                    <button type="submit">
                                        logout @User.Identity.Name<!-- todo stap-11a: laat naam ingelogde gebruiker zien-->
                                    </button>
                                </form>
                            </li>
                        } else {
                            <!--todo lesson 4-6: maak navigatie links aan om te registreren en (latere stap) in te loggen -->
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Users" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Users" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Les2MySportsClub - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>